### ISSUE TITLE
install problem.  main.custom_plugins not defined

### ISSUE THREAD

**Issue by JamesRHarris** [nullm0ose/pwnagotchi-plugin-pisugar3#2]
One suggestion for the installation steps is to double check the main.custom_plugins value in config.toml.  My default.toml has 
`main.custom_plugins = ""` . Following the install steps provided didn't start the plugin. Adding 
`main.custom_plugins = "/etc/pwnagotchi/custom-plugins"` to config.toml resolved the issue.

**Comment by lardAmungus** [comment]
this solved my problem, which was just the plugin not coming in on the display. thanks for sharing!
