### ISSUE TITLE
Question: does it support Pisugar 3 Plus?

### ISSUE THREAD

**Issue by spitfire** [nullm0ose/pwnagotchi-plugin-pisugar3#4]
Does it support Pisugar 3 Plus? I'd like to get it for my Raspberry Pi 3A, and I'm not sure if this plugin will work with it.

**Comment by wpa-2** [comment]
sounds like its Pisugar 3 only 
https://github.com/nullm0ose/pwnagotchi-plugin-pisugar3?tab=readme-ov-file#requirements

**Comment by spitfire** [comment]
Yeah, I’ve read it. I’m not sure ho to understand it - is it only 3 or 3 series (as opposed to 2’s), which is why I’ve asked here hoping @nullm0ose would clarify that.

**Comment by spitfire** [comment]
Looking at https://github.com/PiSugar/PiSugar/wiki/PiSugar-3-Series it seems like they're basically the same with just a different capacity and form factor, the i2c address and registers are the same.

**Comment by spitfire** [comment]
Ok, so while it does not display battery percentage, it does something: it changes between BAT and CHG when I plug/unplug the charger, but the value sits at 0%.

Reading it from i2c as documented returns the value:

```
i2cget 1 0x57 0x2a
WARNING! This program can confuse your I2C bus, cause data loss and worse!
I will read from device file /dev/i2c-1, chip address 0x57, data address
0x2a, using read byte data.
Continue? [Y/n] y
0x4f
```

and it is correct - the battery was at 79% according to PiSugar's web ui.

#edit

after running it in debug mode I found out this:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/pwnagotchi/plugins/__init__.py", line 85, in locked_cb
[2024-02-22 12:22:35,113] [DEBUG] [gps_more] ui_update: {}
    cb(*args, *kwargs)
  File "/usr/local/share/pwnagotchi/available-plugins/pisugar3.py", line 97, in on_ui_update
    if capacity <= self.options['shutdown']:
                   ~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'shutdown'
```

I haven't set this, because I didn't want it to shut down because it was not detected.

this can be worked around by moving last line:

`ui.set('bat', "%2i%%" % capacity)`

above the shutdown handling logic:

```
if capacity <= self.options['shutdown']:
            logging.info('[pisugar3] Empty battery (<= %s%%): shutting down' % self.options['shutdown'])
            ui.update(force=True, new_data={'status': 'Battery exhausted, bye ...'})
            pwnagotchi.shutdown()

```

**Comment by spitfire** [comment]
@nullm0ose sińce you've closed it, can you implement that? It seems someone else has submitted that change in https://github.com/nullm0ose/pwnagotchi-plugin-pisugar3/pull/5
