### ISSUE TITLE
Shows as 0%

### ISSUE THREAD

**Issue by Ianchandler1990** [nullm0ose/pwnagotchi-plugin-pisugar3#8]
Did all the steps and it is showing as 0% , Can upload logs if needed.
![image](https://github.com/user-attachments/assets/48f2804a-c2e7-41d1-83b5-4cd7263eca73)

**Comment by nullm0ose** [comment]
Updated readme file to include section related to troubleshooting and support related to installation.

**Comment by Ianchandler1990** [comment]
You may not help with tech but posting this could of had others who may of had the same issue say what they did. Looking at forks for this plugin and others for the pisuger3 even Reddit seems new users are running into same kind of issue with no fixes so if I find one il update this so if someone sees 0% can see the fix.

**Comment by nullm0ose** [comment]
I appreciate your understanding and I am happy to investigate or provide potential changes if/when you provide any solutions to your specific issue.

**Comment by Ianchandler1990** [comment]
Ok, so went deep into the code as I didn't have time when I first installed this. Added a bunch of logs and found out the update ui part at the end of the code was never called so moved it and now it works.

so you will see "ui.set("bat", f"{capacity}%")" is above the shutdown section

![image](https://github.com/user-attachments/assets/8267ac4d-ecad-454c-816b-1eabd0d4b43e)


[pisugar3.txt](https://github.com/user-attachments/files/17181736/pisugar3.txt)
